apiVersion: apps/v1
kind: Deployment
metadata:
  name: retyc-csi-controller
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: retyc-csi-controller
  template:
    metadata:
      labels:
        app: retyc-csi-controller
    spec:
      serviceAccountName: retyc-csi-controller
      containers:
        - name: csi-provisioner
          image: registry.k8s.io/sig-storage/csi-provisioner:v5.1.0
          args:
            - "--csi-address=/csi/csi.sock"
            - "--leader-election"
            - "--extra-create-metadata"
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
        - name: retyc-csi-controller
          image: retyc/retyc-k8s-csi:dev
          args:
            - "--mode=controller"
            - "--endpoint=unix:///csi/csi.sock"
          envFrom:
            - secretRef:
                name: retyc-csi-credentials
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
      volumes:
        - name: socket-dir
          emptyDir: {}
