{{- if .Values.serviceAccount.controller.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "retyc-csi.controller.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "retyc-csi.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
  {{- with .Values.serviceAccount.controller.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- if .Values.serviceAccount.node.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "retyc-csi.node.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "retyc-csi.labels" . | nindent 4 }}
    app.kubernetes.io/component: node
  {{- with .Values.serviceAccount.node.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
